### ISSUE TITLE
Motorbike Capstone Kanban Board

### ISSUE THREAD

**Issue by SaneMyburg** [SaneMyburg/motorbike-back-end#12]
Hi 😃
[Here is a link to our issues](https://github.com/SaneMyburg/motorbike-back-end/issues)
[Link to kanban board](https://github.com/users/SaneMyburg/projects/5)

In this project, there are 4 team members:
@WilhelmK109 , @AliShahSafdari , @SaneMyburg and @mohametalmeari

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Meltrust** [comment]
Hi @SaneMyburg 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the kanban board.  **_Please add a screenshot._**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by WilhelmK109** [comment]
![Screenshot (1)](https://github.com/SaneMyburg/motorbike-back-end/assets/74548443/857e1728-5563-40b1-8efa-f81150ad383d)

**Comment by WilhelmK109** [comment]
Hi @Meltrust, thanks for your comments and suggestions. We have added the screenshot and we have resubmitted it for review. Thanks

**Comment by Meltrust** [comment]
Hi @SaneMyburg ,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned, pointed, and have descriptions✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
